# Generated by Django 3.2.7 on 2021-09-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unitprice', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('size', models.IntegerField(blank=True)),
                ('color', models.CharField(max_length=50)),
                ('discount', models.IntegerField(default=0)),
                ('photo_main', models.ImageField(upload_to='productimages/%Y/%M/%D/')),
                ('photo_1', models.ImageField(upload_to='productimages/%Y/%M/%D/')),
                ('photo_2', models.ImageField(upload_to='productimages/%Y/%M/%D/')),
                ('photo_3', models.ImageField(upload_to='productimages/%Y/%M/%D/')),
                ('photo_4', models.ImageField(upload_to='productimages/%Y/%M/%D/')),
                ('photo_5', models.ImageField(upload_to='productimages/%Y/%M/%D/')),
                ('photo_6', models.ImageField(upload_to='productimages/%Y/%M/%D/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_hot', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
        ),
    ]
