# Generated by Django 3.2.7 on 2021-09-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='productimages/%Y/%M/%D/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='productimages/%Y/%M/%D/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='productimages/%Y/%M/%D/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='productimages/%Y/%M/%D/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='productimages/%Y/%M/%D/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='productimages/%Y/%M/%D/'),
        ),
    ]
